version: "3.9"
services:
  robinhood:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: robinhood
    volumes:
      - ./tests:/usr/src/app/tests
      - ./robinhood:/usr/src/app/robinhood
    env_file:
      - .env
    ports:
      - 8080:4000
    networks:
      - stockstalker-network
    command: >
      bash -c "coverage run -m unittest discover
      && coverage report -m --fail-under=99"

networks:
  stockstalker-network:
    driver: bridge
