version: "3.9"
services:
  robinhood:
    restart: always
    container_name: robinhood
    image: index.docker.io/starlightromero/stockstalker-robinhood
    env_file:
      - .env
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
