FROM python:3.9-slim-buster

LABEL decription="Development image for StockStalker robinhood."

WORKDIR /usr/src/app

HEALTHCHECK --interval=1m --timeout=5s --retries=2 \
        CMD curl -f http://localhost/robinhood/AAPL || exit 1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements_dev.txt

COPY . .

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run"]
